### PR TITLE
Add SendToPropertyInspector and SendToPlugin code

### PR DESCRIPTION
**Pull request by bennyscetbun**
Hi,
For my own code, my plugin had to exchange data with the propertyInspector but the right calls were missing.
Not anymore :)

### CODE REVIEW

**Comment by tiptronic** [comment]
What's the point of exchanging data with the PI from the CPU-plugin?

**Comment by bennyscetbun** [comment]
Hi,
In the SDK documentation, it s saying that you should copy the plugin in the language you want and then change it to make your own.
The cpu plugin is the only example of Cpp code. By adding in the Common section the missing calls, it should help futur users to make their own plugin :)
I was about to make an other PR to complete the cpu example.
- Add a propertyInspector and use it for changing the icon color for example .
This way, new users would be able to grasp the whole plugin process in Cpp

**Comment by tiptronic** [comment]
Yes, but as a sample plugin we want this to be as lean and clean as possible.
Your additions are welcome, but maybe we should create a plugin stub with those methods included.

**Comment by bennyscetbun** [comment]
It s as you wish.
But in my opinion, it s wierd that the "common" part, doesn't implement the whole "API", even for an example.
Maybe an other repo with the full "Elgato Stream deck" librairy in a language, would be great.

**Comment by Timac** [comment]
Thanks a lot for the pull request. The missing calls in the common part were something I wanted to add.
Note that your change does not include the overridden function in MyStreamDeckPlugin.h and MyStreamDeckPlugin.cpp which causes the compilation of the plugin to fail. I will push another commit to solve that.

The same change will be merged to the MemoryGame plugin which is written in C++ too.

**Comment by bennyscetbun** [comment]
I was about to fix it if you want to.

**Comment by bennyscetbun** [comment]
Too late. ;) You ve done it. Thanks.

**Pull request merged**
