### PR TITLE
Fix CPU usage on windows

### PR DESCRIPTION
**Pull request by kuramochia**
Fix CPU usage on Windows ( #24 ).

### CODE REVIEW

**Comment by kuramochia** [comment]
Hello @ChekTek , Can you check and review this?

**Review by Elgato-AStory — APPROVED** [review]
Looks good to me. Since we can't sync refresh timers with Task Manager, it's not perfectly in sync so some people might still complain, but it's clear that this performance counter is much closer to what task manager is using, if not the same.

**Comment by kuramochia** [comment]
Thank you for your review.
Admittedly, the timing isn't perfect, but I think you'll get the same CPU usage as Task Manager.

**Comment by j-s-a-m** [comment]
Any plans to release this fix? Latest version of CPU plugin available in the Elgato market place is v1.3 of 5. September 2022.

**Pull request merged**
